services:
  mc-radar:
    container_name: mcradar
    image: local-interloper/mcradar
    build:
      context: ./mcradar

    env_file: .env

    depends_on:
      db:
        condition: service_healthy

    networks:
      - mc-radar-network

  api:
    container_name: mcradar-api
    image: local-interloper/mcradar-api
    build:
      context: ./mcradar-api

    env_file: .env

    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8000:8000"

    networks:
      - mc-radar-network

  db:
    container_name: mcradar-db
    image: postgres:18.3
    restart: unless-stopped
    shm_size: 128mb
    command: -c 'max_connections=4096'

    env_file: .env

    volumes:
      - "mc-radar-db-volume:/var/lib/postgresql/18/docker"

    networks:
      - mc-radar-network

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mc-radar-db-volume:


networks:
  mc-radar-network:
